server:
  port: 8080

spring:
  application:
    name: landfunboot
  
  datasource:
    url: jdbc:mysql://lfbgs.hbjk.com.cn:13306/landfunboot?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql@zhy2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://:yingjun1218@175.24.206.249:6379

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

landfun:
  jwt:
    secret: 5XkoUgXdJjWLGMkJII+9Tpk4b0p/76iDfTF4WqzH1Nhxx3e5vb4jhFaWbbUUaFc7h2jAf2B82S+cr9ZLxpiZrQ==
    expire: 2592000

logging:
  level:
    root: INFO
    com.landfun.boot: DEBUG
    org.babyfish.jimmer.sql: INFO
